name: CI/CD Integracion continua

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Bajar el repositorio
        uses: actions/checkout@v3

      - name: Instalar dependenciass
        run: npm install

      - name: Iniciar pruebas
        run: npm test -- --coverage

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/tienda_app:latest .


      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/tienda_app:latest
